catalog_name: mlops_dev
schema_name: ninawils

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - DateTime
  - Temperature
  - Humidity
  - Wind Speed
  - general diffuse flows
  - diffuse flows

target:
  - Zone 1 Power Consumption
  - Zone 2 Power Consumption
  - Zone 3 Power Consumption
