catalog_name: mlops_dev
schema_name: ninawils

prd:
  catalog_name: mlops_prod
  schema_name: house_prices
  pipeline_id: 1818db79-f551-49bb-ad4f-f61cac9d91fc
acc:
  catalog_name: mlops_acc
  schema_name: house_prices
  pipeline_id: 94748db79-f551-49bb-ad4f-f61cac9d91fc
dev:
  catalog_name: mlops_prod
  schema_name: house_prices
  pipeline_id: 0498db79-f551-49bb-ad4f-finac9d91fc

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - DateTime
  - Temperature
  - Humidity
  - Wind Speed
  - general diffuse flows
  - diffuse flows

target:
  - Zone 1 Power Consumption
  # - Zone 2 Power Consumption
  # - Zone 3 Power Consumption
